# Generated by Django 3.2 on 2022-02-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('catagory_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('areaCode', models.UUIDField(primary_key=True, serialize=False)),
                ('stoke', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('no_of_vehicles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('ProductQuantity', models.IntegerField()),
                ('Dateforready', models.DateField()),
                ('Catagory', models.CharField(choices=[('FRUIT', 'FRUIT'), ('VAGETABLE', 'VAGETABLE')], max_length=50)),
                ('SubCatagory', models.CharField(choices=[('potato', 'potato'), ('tomato', 'tomato'), ('onion', 'onion'), ('apple', 'apple'), ('banana', 'banana')], max_length=50)),
                ('vendorareacode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.vendor')),
            ],
        ),
    ]
