# Generated by Django 3.2 on 2022-02-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorinventory',
            old_name='vendorareacode',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='areaname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
