# Generated by Django 3.2 on 2022-02-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('Date_for_ready', models.DateField()),
                ('your_price', models.IntegerField()),
                ('product_type', models.CharField(choices=[('FRUIT', 'FRUIT'), ('VAGETABLE', 'VAGETABLE')], max_length=50)),
            ],
        ),
    ]
