# Generated by Django 3.2 on 2022-02-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorinventory',
            old_name='vendorareacode',
            new_name='vendor',
        ),
    ]
