# Generated by Django 3.2 on 2022-02-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20220217_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='areaCode',
        ),
        migrations.AddField(
            model_name='vendorinventory',
            name='acceptbutton',
            field=models.CharField(default=False, max_length=50, verbose_name='Accept'),
        ),
        migrations.AddField(
            model_name='vendorinventory',
            name='deniedbutton',
            field=models.CharField(default=False, max_length=50, verbose_name='Denied'),
        ),
    ]
