# Generated by Django 3.2 on 2022-02-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20220217_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinventory',
            name='acceptbutton',
            field=models.BooleanField(default=False, max_length=50, verbose_name='Accept'),
        ),
        migrations.AlterField(
            model_name='vendorinventory',
            name='deniedbutton',
            field=models.BooleanField(default=False, max_length=50, verbose_name='Denied'),
        ),
    ]
