# Generated by Django 3.2 on 2022-02-18 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20220217_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse.vendorinventory'),
        ),
    ]
