# Generated by Django 3.2 on 2022-02-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_warehouse_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinventory',
            name='deniedbutton',
        ),
    ]
