# Generated by Django 3.2 on 2022-02-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_vendorinventory_sell_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorinventory',
            old_name='dateforready',
            new_name='date_for_ready',
        ),
        migrations.RenameField(
            model_name='vendorinventory',
            old_name='productname',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='vendorinventory',
            old_name='productquantity',
            new_name='product_quantity',
        ),
    ]
