# Generated by Django 3.2 on 2022-02-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20220218_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='is_ready',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='procuct_price',
        ),
    ]
