# Generated by Django 3.2 on 2022-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20220218_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_ready',
            field=models.BooleanField(default=False, max_length=50, verbose_name='Ready to Sell'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='procuct_price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
