# Generated by Django 3.2 on 2022-02-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryDate',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='productQuntity',
            new_name='product_quntity',
        ),
    ]
