# Generated by Django 3.2 on 2022-02-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Pin',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='Area_code',
            new_name='area_code',
        ),
    ]
