# Generated by Django 3.2 on 2022-02-14 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_data',
            new_name='customer_data',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='user_data',
            new_name='vendor_data',
        ),
    ]
