# Generated by Django 3.2 on 2022-02-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_productquntity_product_productquntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productquntity',
            new_name='product_quntity',
        ),
    ]
