# Generated by Django 3.2 on 2022-02-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_auto_20220218_0932'),
        ('product', '0003_rename_productquntity_product_product_quntity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
            preserve_default=False,
        ),
    ]
