# Generated by Django 3.2 on 2022-02-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text='Per Kg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quntity',
            field=models.IntegerField(help_text='In Kg'),
        ),
    ]
